openapi: 3.0.0
info:
  title: clevabit API
  description: |
    The clevabit API is organized around the [REST](http://en.wikipedia.org/wiki/Representational_State_Transfer) principle. It features predictable resource-oriented HTTP URLs.

    While all request bodies are expected in JSON encoded request objects, all responses provided
    by the API are encoded as [CBOR](https://www.clevabit.com/developers/#/?id=cbor)
    objects, except stated otherwise.

    The API uses standard HTTP verbs, and response codes.
  version: 1.0.0
servers:
  - description: |
      The Sandbox provides demo data from testing devices, which are not
      related to any real world customer. That said, the Sandbox cannot access real
      customer data.

      To login into the Sandbox, use the same application id and application key to
      be used against the production environment, however username/email and password
      are different and valid only with the sandbox environment.

      Apart from that, the sandbox has one additional feature, which is not available in the
      production environment. With an accept HTTP header in request set to application/json
      you can ask the Sandbox version of the API to respond with JSON instead of CBOR
      objects. This may make debugging of responses much easier.

      Furthermore, the Sandbox has relaxed Rate Limits, therefore is suited for development
      and debugging uses.
    url: 'https://sandbox.clevabit.com/api/v1'
  - description: |
      The Production environment is used for real world requests, being directed towards real customer data.

      This API must not be used for development or debugging.
    url: 'https://api-eu.clevabit.com/api/v1'
paths:
  '/customers/{customerid}':
    get:
      summary: er
      tags: []
      responses: {}
      operationId: get-customers-customerid
    parameters:
      - schema:
          type: string
          format: uuid
        name: customerid
        in: path
        required: true
        description: "The customer's UUID"
  /auth:
    post:
      summary: auth
      tags: []
      responses: {}
      operationId: post-auth
components:
  schemas: null
  securitySchemes:
    Bearer Token:
      type: http
      scheme: bearer
      description: "API calls to any endpoint other than _/auth/_ require a valid authorization token.\n\nBy default, the authorization request requires a valid CSRF (Cross Site Request Forgery)\ntoken, which is provided by the server and only valid for a single form submission. In\naddition the CSRF token is only valid for limited amount of time.\n\nFor applications that cannot show an HTML login form, or partner systems that use direct\nserver to server communication, the API provides a way to login a third party (user) by\nproviding its unique application id (_x-app-id_) and application key (_x-app-key_), as\nwell as the customer id (_x-app-cid_) it wants to be logged in with.\n\nRequests using the application id and application key to authenticate as a valid\nlogin mechanism, still need to provide a valid username/email address and password.\n\nFor partners reading data for multiple users, a special account with access to multiple\ncustomer accounts may be provided. Otherwise multiple requests (one per customer account)\nare required. \n\nTo request an application id and application key, please contact your clevabit\nrepresentative."
